# Default application properties.
# 
# Create an application.yml on your working directory to override these values,
# or application-X.yml where X is the name of the active profile provided via
# the JVM argument -Dspring.profiles.active=X

# Default profile
server:
  port: 8080
  address: "0.0.0.0"
  
  compression:
    enabled: true
    mime-types: 
      - application/json
      - application/xml
      - image/svg+xml
      - text/javascript
      - text/css
      - text/html
      - text/plain
      - text/xml

  # ssl config here

spring:
  mvc.formcontent.putfilter.enabled: false
  resources.cache-period: 86400
  http.multipart:
    max-file-size: 250MB
    max-request-size: 250MB

logging:
  pattern:
    console: "${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file:  "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

debugMode: false


---
spring:
  profiles: development

debugMode: true

logging:
  level:
    net.solarnetwork: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

---
spring:
  profiles: production
